name: Validate Java e2e
# To-Do in final review add filter by main branch
on: 
  push:
  pull_request:
jobs:
  setup-java-major-versions:
    name: Setup Java for major versions ${{ matrix.java }} ${{ matrix.os }} ${{ matrix.distribution }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        java:
        - '8'
        - '11'
        - '14'
        - '15'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java ${{ matrix.java }} 'jdk' ${{ matrix.distribution }}
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-package: 'jdk'
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version


  setup-java-major-minor-versions:
    name: Setup Java for major minor versions ${{ matrix.java }} ${{ matrix.os }} ${{ matrix.distribution }}
    needs: setup-java-major-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        java:
        - '8.0'
        - '11.0'
        - '14.0'
        - '15.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java ${{ matrix.java }} jdk ${{ matrix.distribution }}
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-package: 'jdk'
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version

  setup-java-ea-versions:
    name: Setup Java for ea versions ${{ matrix.java }} ${{ matrix.os }} ${{ matrix.distribution }}
    needs: setup-java-major-minor-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        java-package: ['jdk']
        java:
        - '14.0-ea'
        - '15.0-ea'
        - '14-ea'
        - '15-ea'
        include:
          - distribution: 'zulu'
            java-package: jdk+fx
            java: '8'
            os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java ${{ matrix.java }} ${{ matrix.java-package }} ${{ matrix.distribution }}
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-package: ${{ matrix.java-package }}
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version

  setup-java-major-minor-versions-for-jre:
    name: Setup Java for major minor versions ${{ matrix.java }} ${{ matrix.os }} ${{ matrix.distribution }}
    needs: setup-java-major-minor-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        java-package: ['jre']
        java:
        - '8'
        - '8.0'
        - '11'
        - '11.0'
        - '12'
        - '12.0'
        - '14'
        - '14.0'
        - '15'
        - '15.0'
        exclude:
          - os: macos-latest
            distribution: 'zulu'
            java-package: 'jre'
            java: '12.0'
          - os: ubuntu-latest
            distribution: 'zulu'
            java-package: 'jre'
            java: '12.0'
        include:
          - distribution: 'zulu'
            java-package: jre+fx
            java: '8'
            os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java ${{ matrix.java }} ${{ matrix.java-package }} ${{ matrix.distribution }}
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-package: ${{ matrix.java-package }}
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version
